#!/usr/bin/env node
// Generates the profile wordmark:
//   assets/banner.svg   880x150
//
// The name is set in the same spirit as the Loom shell's ANSI Shadow header
// (src/banner.h): solid block capitals with a hard offset shadow. It is drawn
// as <rect> runs from the 5x7 bitmap font rather than SVG <text>, because
// GitHub proxies images through camo, which blocks webfonts — a <text> element
// asking for a block font silently falls back to Arial on the rendered profile.
//
// The whole name sits on ONE line by construction: it is measured, and the
// scale is chosen so it fits the safe width with margin to spare.
//
// Everything else in the README is now hand-authored art or plain Markdown, so
// this is the only generated asset left.
//
// Run: node scripts/gen-art.mjs   (--force to overwrite hand-edited files)

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { doc, rect } from './lib/svg.mjs';
import { text, textWidth, GLYPH_H } from './lib/font.mjs';
import { brand } from './lib/palette.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

// Everything this script writes carries the marker below. Anything in assets/
// without it is hand-authored art, so leave it alone — re-running the generator
// must never eat the real artwork.
const MARK = '<!--generated by scripts/gen-art.mjs-->';

const out = (name, svg) => {
  const path = resolve(ROOT, 'assets', name);
  if (!force && existsSync(path) && !readFileSync(path, 'utf8').includes(MARK)) {
    console.log(`  ${name}  kept — hand-authored, not overwriting`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, MARK + svg);
  console.log(`  ${name}  ${(svg.length / 1024).toFixed(1)} KB`);
};

// ---------------------------------------------------------------- banner ----

const NAME = 'MANAN CHHABHAYA';
const HANDLE = '@CHHABHAYAMANAN';

const W = 880;
const H = 150;
const SAFE = 780;    // widest the name may be; the rest is breathing room
const DEPTH = 6;     // shadow offset, in px

function banner() {
  // Pick the largest whole scale that still fits on one line. At 15 characters
  // this lands on 8; the guard is here so a longer name shrinks instead of
  // wrapping or overflowing.
  const units = textWidth(NAME);
  const scale = Math.max(2, Math.floor(SAFE / units));
  const nameW = units * scale;
  const nameH = GLYPH_H * scale;

  const x = Math.round((W - nameW) / 2);
  const y = 30;

  const hScale = 2;
  const handleW = textWidth(HANDLE) * hScale;
  const hx = Math.round((W - handleW) / 2);
  const hy = y + nameH + DEPTH + 22;

  const parts = [rect(0, 0, W, H, brand.bg)];

  // Three passes, back to front: deep shadow, mid bevel, then the face. That
  // stack is what gives the ANSI Shadow letters their extruded look.
  parts.push(text(NAME, { x: x + DEPTH, y: y + DEPTH, scale, fill: brand.shadow }));
  parts.push(text(NAME, { x: x + 3, y: y + 3, scale, fill: brand.bevel }));
  parts.push(text(NAME, { x, y, scale, fill: brand.face }));

  // A charge bar under the name, broken into cells so it reads as pixel art
  // rather than a rule.
  const barY = y + nameH + DEPTH + 8;
  for (let i = 0; i < 30; i++) {
    parts.push(rect(x + i * (nameW / 30), barY, Math.floor(nameW / 30) - 3, 4, i % 5 === 4 ? brand.bevel : brand.dim));
  }

  parts.push(text(HANDLE, { x: hx, y: hy, scale: hScale, fill: brand.muted }));

  return doc({
    width: W, height: H,
    title: 'Manan Chhabhaya — @ChhabhayaManan',
    desc: 'The name Manan Chhabhaya set in block capitals with a hard drop shadow, above the handle @ChhabhayaManan.',
    body: parts.join(''),
  });
}

// ------------------------------------------------------------------ main ----

console.log('generating art');
out('banner.svg', banner());
console.log('done');
